(function(){
'use strict';
const A=window.JAVA_APP,$=A.$,esc=A.esc;let war=null;
function init(l){war={lab:l,time:18,impact:null,evidence:new Set(),hyp:{},cause:'',causeLocked:false,recovery:'',verify:new Set(),comm:'',scores:{eng:20,con:20,pm:20},finished:false,feedback:''}}
function layers(){return new Set([...war.evidence].map(id=>war.lab.evidence.find(e=>e.id===id)?.layer).filter(Boolean))}
function cls(n){return n>=85?'good':n>=70?'warn':'bad'}
function scores(){return `<div class="j-score-grid">${[['eng','Engineer'],['con','Consultant'],['pm','PM / PMO']].map(([k,t])=>`<div class="j-score ${cls(war.scores[k])}"><span>${t}</span><b>${Math.max(0,Math.min(100,Math.round(war.scores[k])))}</b></div>`).join('')}</div>`}
function impact(){return `<section class="j-card"><div class="j-kicker">FIRST DECISION</div><h2>顧客・業務影響を先に固定する</h2><p class="j-muted">残高照会の一部が失敗し、振込は正常。原因を当てる前にSeverityを決めます。</p><div class="j-option-grid"><button class="j-option" data-impact="sev1">SEV1：全決済停止・社会影響級</button><button class="j-option" data-impact="sev2">SEV2：重要機能の部分劣化。緊急対応する</button><button class="j-option" data-impact="sev3">SEV3：内部限定で顧客影響なし</button></div></section>`}
function evidenceBoard(l){return war.evidence.size?[...war.evidence].map(id=>{const e=l.evidence.find(x=>x.id===id);return `<article class="j-evidence-card"><header><span>${esc(e.layer)}</span><span>-${e.cost}m</span></header><h3>${esc(e.label)}</h3><code>${esc(e.value)}</code><p>${esc(e.insight)}</p></article>`}).join(''):'<div class="j-empty">症状だけでは原因を確定できません。<br>価値の高いEvidenceから調べます。</div>'}
function resolution(l){return `<section class="j-war-layout"><div class="j-card"><div class="j-kicker">SAFE RECOVERY</div><h2>可逆的に影響を止める</h2><div class="j-action-grid">${l.recoveries.map(a=>`<button class="j-action ${war.recovery===a.id?'selected '+(a.correct?'correct':'wrong'):''}" data-recovery="${a.id}" ${war.recovery?'disabled':''}>${esc(a.label)}</button>`).join('')}</div></div><div class="j-card"><div class="j-kicker">VERIFY / RECONCILE</div><h2>技術Greenだけで閉じない</h2><div class="j-check-grid">${l.verifications.map(v=>`<label><input type="checkbox" data-verify="${v.id}" ${war.verify.has(v.id)?'checked':''} ${war.finished?'disabled':''}><span>${esc(v.label)}</span></label>`).join('')}</div><div class="j-cause-form" style="margin-top:10px"><label>状況共有<select id="warComm" ${war.finished?'disabled':''}><option value="">選択してください</option><option value="facts" ${war.comm==='facts'?'selected':''}>Fact・影響・Unknown・Action・次回更新時刻を分ける</option><option value="guess" ${war.comm==='guess'?'selected':''}>原因候補を確定原因として発表</option><option value="silent" ${war.comm==='silent'?'selected':''}>完全復旧まで共有しない</option></select></label><button class="j-primary" id="finishWar" ${war.recovery&&war.verify.size&&war.comm&&!war.finished?'':'disabled'}>Score / Sign-off</button></div></div></section>`}
function workspace(l){const ls=layers(),ready=war.evidence.size>=3&&ls.size>=3;return `<section class="j-war-layout"><div class="j-card"><div class="j-kicker">FREE INVESTIGATION</div><h2>どこから調べる？</h2><div class="j-war-budget">⏱ Evidence Budget <b>${war.time} min</b></div><div class="j-evidence-choices" style="margin-top:10px">${l.evidence.map(e=>`<button class="j-evidence-button ${war.evidence.has(e.id)?'selected':''}" data-war-evidence="${e.id}" ${war.evidence.has(e.id)?'disabled':''}><span><b>${esc(e.label)}</b><span>${esc(e.layer)} / -${e.cost} min</span></span><span>${war.evidence.has(e.id)?'✓':'調査'}</span></button>`).join('')}</div></div><div class="j-card"><div class="j-kicker">EVIDENCE BOARD</div><h2>確認済みの事実</h2><div class="j-evidence-board">${evidenceBoard(l)}</div></div></section><section class="j-war-layout"><div class="j-card"><div class="j-kicker">HYPOTHESIS BOARD</div><h2>候補を残す・消す</h2><div class="j-hyp-grid">${l.hypotheses.map(h=>`<article class="j-hyp ${war.hyp[h.id]||''}"><b>${esc(h.label)}</b><button data-hyp="${h.id}" data-status="investigate">調査中</button><button data-hyp="${h.id}" data-status="hot">有力</button><button data-hyp="${h.id}" data-status="ruledout">除外</button></article>`).join('')}</div></div><div class="j-card"><div class="j-kicker">CAUSE DECLARATION</div><h2>原因を指摘する</h2><div class="j-gate ${ready?'ready':''}"><b>${war.evidence.size} Evidence / ${ls.size} Layers</b><span>${ready?'宣言可能':'3 Evidence・3 Layers以上必要'}</span></div><div class="j-cause-form"><label>Primary Cause<select id="warCause" ${war.causeLocked?'disabled':''}><option value="">選択してください</option>${l.hypotheses.map(h=>`<option value="${h.id}" ${war.cause===h.id?'selected':''}>${esc(h.label)}</option>`).join('')}</select></label><button class="j-primary" id="lockCause" ${ready&&!war.causeLocked?'':'disabled'}>原因を確定する</button></div>${war.feedback?`<div class="j-feedback">${esc(war.feedback)}</div>`:''}</div></section>${war.causeLocked?resolution(l):''}`}
function result(l){const pass=war.scores.eng>=85&&war.scores.con>=85&&war.scores.pm>=85;return `<section class="j-card"><div class="j-kicker">FINAL SIGN-OFF</div><h2>${pass?'✓ JAVA APPLICATION SIGN-OFF':'REVIEW REQUIRED'}</h2>${scores()}<p class="j-muted">${pass?'Application・JVM・DB・Release・業務Verificationを横断して判断できました。':'Evidence、Recovery、業務照合、共有を見直します。'}</p>${pass?A.completeBanner(l):''}</section>`}
function render(l){if(!war||war.lab.id!==l.id)init(l);document.querySelector('#app').innerHTML=`<section class="j-card j-lab-hero"><div class="j-lab-nav"><a href="#home">← 20 Labs</a><span class="j-phase-badge">${esc(l.phaseLabel)}</span></div><div class="j-kicker">LAB 20 / CAPSTONE</div><h1>${esc(l.title)}</h1><p class="j-home-lead">${esc(l.subtitle)}</p>${A.journey(l)}<div class="j-chip-row"><span>原因は未確定</span><span>Free Investigation</span><span>TRI-ROLE 85</span></div></section>${A.needGrid(l)}${war.impact===null?impact():workspace(l)}${war.finished?result(l):''}${A.lenses(l)}`;bind(l);A.top()}
function bind(l){document.querySelectorAll('[data-impact]').forEach(b=>b.onclick=()=>{war.impact=b.dataset.impact;if(war.impact==='sev2'){war.scores.con+=10;war.scores.pm+=10}else{war.scores.con-=6;war.scores.pm-=8}render(l)});document.querySelectorAll('[data-war-evidence]').forEach(b=>b.onclick=()=>{const e=l.evidence.find(x=>x.id===b.dataset.warEvidence);if(!e||war.evidence.has(e.id)||war.time<e.cost)return;war.evidence.add(e.id);war.time-=e.cost;['eng','con','pm'].forEach(k=>war.scores[k]+=e.points?.[k]||0);render(l)});document.querySelectorAll('[data-hyp]').forEach(b=>b.onclick=()=>{war.hyp[b.dataset.hyp]=b.dataset.status;render(l)});const c=$('#warCause');if(c)c.onchange=()=>war.cause=c.value;const lock=$('#lockCause');if(lock)lock.onclick=()=>{if(!war.cause)return;war.causeLocked=true;if(war.cause===l.correctCause){war.scores.eng+=18;war.scores.con+=8;war.scores.pm+=5;war.feedback='Cause DeclarationをEvidenceで固定しました。'}else{war.scores.eng-=15;war.scores.con-=10;war.feedback='Evidenceとの整合を再確認してください。'}render(l)};document.querySelectorAll('[data-recovery]').forEach(b=>b.onclick=()=>{const x=l.recoveries.find(v=>v.id===b.dataset.recovery);war.recovery=x.id;['eng','con','pm'].forEach(k=>war.scores[k]+=x.points?.[k]||0);render(l)});document.querySelectorAll('[data-verify]').forEach(x=>x.onchange=()=>{x.checked?war.verify.add(x.dataset.verify):war.verify.delete(x.dataset.verify);render(l)});const comm=$('#warComm');if(comm)comm.onchange=()=>{war.comm=comm.value;render(l)};const finish=$('#finishWar');if(finish)finish.onclick=()=>{if(war.finished)return;l.verifications.forEach(v=>{if(war.verify.has(v.id)){if(v.correct)['eng','con','pm'].forEach(k=>war.scores[k]+=v.points?.[k]||0);else{war.scores.eng-=4;war.scores.con-=4;war.scores.pm-=3}}});if(war.comm==='facts'){war.scores.con+=10;war.scores.pm+=14}else{war.scores.con-=8;war.scores.pm-=12}Object.keys(war.scores).forEach(k=>war.scores[k]=Math.max(0,Math.min(100,Math.round(war.scores[k]))));war.finished=true;const pass=war.scores.eng>=85&&war.scores.con>=85&&war.scores.pm>=85;if(pass){A.set(A.key(20),'true');A.set(A.WAR_KEY,JSON.stringify({...war.scores,passed:true,date:new Date().toISOString()}))}render(l)}}
A.warLab=render;
})();
