(function(){
'use strict';
const LABS=window.JAVA_LABS||[],PREFIX='java_app_lab',WAR_KEY='java_app_warroom_result';
const PHASES=[['build','01–05','Applicationを組み立てる','RequestがJava/JVMへ届き、ArtifactとしてLinux上で動くまで。'],['guided','06–10','WebとDatabaseを結ぶ','HTTP契約、責務、JDBC、Connection Pool、Transaction。'],['diagnose','11–15','本番Evidenceを読む','Exception、Thread、Memory、Retry、Observability。'],['operate','16–19','統制して運ぶ','Security、Secret、Messaging、Container / Cloud Release。'],['warroom','20','Java War Room','False Greenを自由捜査し、業務まで復旧確認する。']];
const JOURNEY=[['client','📱 Client'],['edge','🚪 Edge / LB'],['app','☕ Java App'],['runtime','🧠 JVM'],['data','💾 DB'],['queue','📨 MQ']];
const STACK=[['Customer / Channel','Browser・Mobile App・外部System。ApplicationへRequestを送る。'],['HTTP / API Contract','Method・Path・Status・JSON・Timeout・Idempotency。外部との約束。'],['Application','Controller・Use Case・Business Rule・Data Access。業務を実行する層。'],['Framework','Spring Boot等。Applicationを組み立て、運転機能を提供する。'],['Java Runtime','JDK・JVM・Class File・Thread・Heap・GC。Java Codeを実行する基盤。'],['Integration','JDBC・DataSource・JMS・IBM MQ・API Client。外部境界。'],['OS / Platform','Linux Process・Port・Container・Cloud Runtime。Applicationの足場。'],['Evidence / Governance','Log・Metrics・Trace・JFR・Artifact・Support Matrix・Runbook。']];
const JAVA_TERMS=[['Java','業務Applicationを記述するProgramming Language。JavaScriptとは別。'],['JVM','Class Fileを読み、Thread・Memory・GCを管理して実行する基盤。'],['JDK','Compiler・Runtime・診断Toolを含むToolset。'],['Spring Boot','Spring Applicationを構築・起動・設定・監視しやすくするFramework。'],['JAR / WAR','ApplicationやLibraryを配布するPackaging形式。'],['JDBC','JavaからRelational Databaseを操作する標準API。'],['DataSource','Connection取得方法を抽象化する入口。'],['Connection Pool','有限なDB Connectionを再利用し、待ち・上限・返却を管理する仕組み。'],['@Transactional','SpringのTransaction境界を宣言する代表的Annotation。'],['Thread','JVM内で処理を進める実行単位。'],['Heap / GC','Objectを置く領域と、不要Objectを回収する仕組み。'],['JFR','JVM Eventを記録し、CPU・Allocation・Lock・I/O等を分析する仕組み。'],['Actuator','Health・Metrics等を公開するSpring Bootの運用機能。'],['Trace / Span','一つのRequestを処理区間に分けて追う観測Data。'],['JMS / IBM MQ','JavaのMessaging APIと、Enterprise Messaging製品の一例。'],['Idempotency','同じ依頼を複数回受けても、業務結果を一度分に保つ性質。'],['Canary Release','一部Trafficへ先に配布し、停止条件を見ながら展開する方式。']];
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const get=k=>{try{return localStorage.getItem(k)}catch(e){return null}},set=(k,v)=>{try{localStorage.setItem(k,v)}catch(e){}};
const key=id=>PREFIX+String(id).padStart(2,'0')+'_complete',done=id=>get(key(id))==='true';
let evidence=new Set(),feedback='',modal=null;
function top(){requestAnimationFrame(()=>requestAnimationFrame(()=>window.scrollTo({top:0,left:0,behavior:'instant'})))}
function stackModal(){if(modal)return modal;modal=document.createElement('div');modal.className='j-modal';modal.hidden=true;modal.innerHTML=`<div class="j-modal-backdrop" data-close-stack></div><section class="j-modal-panel" role="dialog" aria-modal="true" aria-labelledby="javaStackTitle"><header class="j-modal-head"><div><div class="j-kicker">APPLICATION STACK MAP</div><h2 id="javaStackTitle">Javaを、Application Stackの中に置く</h2><p class="j-muted j-small">製品名を孤立して覚えず、役割・実行基盤・外部境界・Evidenceを分けます。</p></div><button class="j-modal-close" type="button" data-close-stack aria-label="閉じる">×</button></header><div class="j-stack-layers">${STACK.map(x=>`<div class="j-stack-layer"><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div><div class="j-stack-boundaries"><b>混同しない：</b><br>Javaは言語。JVMは実行基盤。JDKはToolset。Spring BootはFramework。TomcatはServlet Container。JDBCはDatabase接続API。JMSはMessaging APIです。</div><details class="j-java-terms"><summary>📖 Java固有用語を、役割から確認する</summary><div>${JAVA_TERMS.map(x=>`<article><b>${esc(x[0])}</b><span>${esc(x[1])}</span></article>`).join('')}</div></details></section>`;document.body.appendChild(modal);modal.querySelectorAll('[data-close-stack]').forEach(x=>x.onclick=closeStack);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!modal.hidden)closeStack()});return modal}
function openStack(){const m=stackModal();m.hidden=false;document.body.style.overflow='hidden';m.querySelector('.j-modal-close').focus()}
function closeStack(){if(!modal)return;modal.hidden=true;document.body.style.overflow=''}
document.querySelectorAll('[data-open-stack]').forEach(b=>b.onclick=openStack);
function systemLine(){return `<div class="j-system-line">${[['📱','Client'],['🚪','LB / API'],['☕','Java App','java'],['🧠','JVM'],['💾','Database','data'],['📨','Messaging','queue']].map(x=>`<div class="j-system-node ${x[2]||''}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join('')}</div>`}
function home(){const n=LABS.filter(l=>done(l.id)).length,next=LABS.find(l=>!done(l.id))?.id||20,pct=Math.round(n/20*100);$('#app').innerHTML=`<section class="j-card j-home-hero"><div class="j-kicker">ENTERPRISE APPLICATION / 20 LABS</div><h1>通信とDataの間で、<br><span>業務を動かす。</span></h1><p class="j-home-lead">Java文法を暗記する教材ではありません。HTTPを受け、業務Ruleを実行し、DatabaseやMessagingと連携し、JVM・Linux・Cloud上で運転するApplication層を、Evidenceと判断で学びます。</p><div class="j-chip-row"><span>Java / JVM / JDK</span><span>Spring Boot</span><span>JDBC / Transaction</span><span>Thread / Heap / GC</span><span>JMS / IBM MQ</span><span>Engineer / Consultant / PM</span></div><div class="j-home-actions"><a class="j-primary" href="#lab${String(next).padStart(2,'0')}">${n?'続きを開く':'Lab01から始める'} →</a><button class="j-secondary" type="button" data-open-stack-home>Stack Mapを見る</button></div></section><section class="j-dashboard"><div class="j-card"><div class="j-kicker">REQUEST JOURNEY</div><h2>Applicationは、Systemの中央にいる</h2><p class="j-muted j-small">入口のHTTP、内部のJVM、正本Data、非同期連携を一つのRequestとして追います。</p>${systemLine()}</div><div class="j-card j-progress-card"><div><div class="j-kicker">PROGRESS</div><h2>${n===20?'Java Package修了':'次は Lab '+String(next).padStart(2,'0')}</h2><p class="j-muted j-small">${n===20?'Field Incident Gateへ進めます。':'必要Evidenceを見て判断した後に修了を記録します。'}</p></div><div class="j-progress-ring" style="--progress:${pct}%"><b>${n}</b><span>/ 20 Labs</span></div></div></section><div class="j-section-head"><h2>5つのLearning Phase</h2><span>Build → Guided → Diagnose → Operate → War Room</span></div><section class="j-phase-grid">${PHASES.map(p=>`<article class="j-phase-card"><small>${p[1]} / ${p[0].toUpperCase()}</small><h3>${p[2]}</h3><p>${p[3]}</p><b>${LABS.filter(l=>l.phase===p[0]&&done(l.id)).length} / ${LABS.filter(l=>l.phase===p[0]).length} COMPLETE</b></article>`).join('')}</section><div class="j-section-head"><h2>20 Labs</h2><span>初心者には用語補助、経験者にはExpert Lens</span></div><section class="j-lab-grid">${LABS.map(l=>`<a class="j-lab-link ${done(l.id)?'complete':''}" href="#lab${String(l.id).padStart(2,'0')}"><div class="j-lab-num">${String(l.id).padStart(2,'0')}</div><div class="j-lab-copy"><small>${esc(l.phaseLabel)}</small><h3>${esc(l.title)}</h3><p>${esc(l.subtitle)}</p></div><div class="j-lab-state">${done(l.id)?'✓ 修了':'開く →'}</div></a>`).join('')}</section>`;$('[data-open-stack-home]').onclick=openStack;top()}
function journey(l){const a=new Set(l.journey||[]);return `<div class="j-journey">${JOURNEY.map(([id,label])=>`<div class="j-journey-node ${a.has(id)||[...a].some(x=>String(x).includes(id))?'active':''}"><b>${label}</b><span>${a.has(id)?'今回の焦点':'Context'}</span></div>`).join('')}</div>`}
function needGrid(l){return `<section class="j-card"><div class="j-kicker">NEED BEFORE TOOL</div><h2>製品名より先に、必要性を理解する</h2><div class="j-need-grid"><article class="j-need"><small>01 / もともと何がある？</small><h3>現在地</h3><p>${esc(l.already)}</p></article><article class="j-need"><small>02 / 無いと何に困る？</small><h3>問題</h3><p>${esc(l.problem)}</p></article><article class="j-need"><small>03 / どんな機能が必要？</small><h3>必要能力</h3><p>${esc(l.capability)}</p></article><article class="j-need"><small>04 / なぜ今回はこれ？</small><h3>選択</h3><p>${esc(l.choice)}</p></article></div><div class="j-boundary"><b>境界：</b> ${esc(l.boundary)}</div></section>`}
function beforeAfter(l){return `<div class="j-before-after"><article class="j-state-box"><small>BEFORE</small><h3>まだ揃っていない状態</h3><div class="j-state-parts">${l.before.map(x=>`<span>${esc(x)}</span>`).join('')}</div></article><div class="j-state-arrow">→</div><article class="j-state-box"><small>AFTER</small><h3>追加・設計後の状態</h3><div class="j-state-parts">${l.after.map(x=>`<span>${esc(x)}</span>`).join('')}</div></article></div>`}
function codePanel(l){return `<div class="j-code"><div class="j-code-head"><span>CODE / COMMAND LENS</span><span>読むための代表例</span></div><pre><code>${esc(l.code)}</code></pre></div><div class="j-code-notes">${l.codeNotes.map(x=>`<div class="j-code-note"><code>${esc(x[0])}</code><span>${esc(x[1])}</span></div>`).join('')}</div>`}
function evidenceLayout(l){return `<div class="j-evidence-layout"><div><div class="j-kicker">EVIDENCE SELECTOR</div><h2>何を見れば、事実に近づける？</h2><p class="j-muted j-small">仮説を残す／消すために必要なEvidenceを選びます。</p><div class="j-evidence-choices">${l.evidence.map(e=>`<button class="j-evidence-button ${evidence.has(e.id)?'selected':''}" type="button" data-evidence="${esc(e.id)}"><span><b>${esc(e.label)}</b><span>${esc(e.layer)}</span></span><span>${evidence.has(e.id)?'✓':'取得'}</span></button>`).join('')}</div></div><div><div class="j-kicker">EVIDENCE BOARD</div><h2>集めた事実</h2><div class="j-evidence-board">${evidence.size?[...evidence].map(id=>{const e=l.evidence.find(x=>x.id===id);return `<article class="j-evidence-card"><header><span>${esc(e.layer)}</span><span>${esc(e.label)}</span></header><code>${esc(e.value)}</code><p>${esc(e.insight)}</p></article>`}).join(''):'<div class="j-empty">まだEvidenceはありません。<br>左から確認材料を選びます。</div>'}</div></div></div>`}
function completeBanner(l){const next=Math.min(20,l.id+1);return `<div class="j-complete-banner"><b>✓ Lab ${String(l.id).padStart(2,'0')} 修了</b><span>役割・境界・Evidence・判断をつなげました。</span><div class="j-next-actions"><a class="j-primary" href="${l.id===20?'../field-casebook/':'#lab'+String(next).padStart(2,'0')}">${l.id===20?'Field Incident Gateへ':'次のLabへ →'}</a><a class="j-secondary" href="#home">20 Labsへ</a></div></div>`}
function decisionPanel(l){const gate=evidence.size>=l.decision.minEvidence;return `<section class="j-decision"><div class="j-kicker">DECISION GATE</div><h2>${esc(l.decision.prompt)}</h2><div class="j-gate ${gate?'ready':''}"><b>Evidence ${evidence.size} / ${l.decision.minEvidence}</b><span>${gate?'判断できます。':'先に必要なEvidenceを確認します。'}</span></div><div class="j-option-grid">${l.decision.options.map(o=>`<button class="j-option" type="button" data-option="${o.id}" ${gate?'':'disabled'}>${esc(o.label)}</button>`).join('')}</div>${feedback?`<div class="j-feedback ${feedback.startsWith('✓')?'correct':''}">${esc(feedback)}</div>`:''}${done(l.id)?completeBanner(l):''}</section>`}
function lenses(l){return `<section class="j-card"><div class="j-kicker">TRI-ROLE LENS</div><h2>同じ技術を、3つの責任から読む</h2><div class="j-lens-grid"><article class="j-lens"><b>🧑‍💻 Engineer</b><p>${esc(l.roles.eng)}</p></article><article class="j-lens"><b>🧭 Consultant</b><p>${esc(l.roles.con)}</p></article><article class="j-lens"><b>📋 PM / PMO</b><p>${esc(l.roles.pm)}</p></article></div><ul class="j-question-list">${l.questions.map(q=>`<li>${esc(q)}</li>`).join('')}</ul></section><section class="j-main-grid"><details class="j-expert"><summary>🧠 Expert Lens — 玄人向けの論点</summary><p>${esc(l.expert)}</p></details><div class="j-finance"><b>🏦 Financial Context</b><br>${esc(l.financial)}</div></section>`}
function normalLab(l){$('#app').innerHTML=`<section class="j-card j-lab-hero"><div class="j-lab-nav"><a href="#home">← 20 Labs</a><span class="j-phase-badge">${esc(l.phaseLabel)}</span></div><div class="j-kicker">LAB ${String(l.id).padStart(2,'0')} / ${esc(l.focus.toUpperCase())}</div><h1>${esc(l.title)}</h1><p class="j-home-lead">${esc(l.subtitle)}</p>${journey(l)}<div class="j-stage-note">Request Journeyのどこを学んでいるかを、上のNodeで示します。</div></section>${needGrid(l)}<section class="j-main-grid"><div class="j-card"><div class="j-kicker">SYSTEM DIFF</div><h2>何が増え、どこに境界ができる？</h2>${beforeAfter(l)}</div><div class="j-card">${codePanel(l)}</div></section><section class="j-card">${evidenceLayout(l)}</section>${decisionPanel(l)}${lenses(l)}`;document.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{evidence.has(b.dataset.evidence)?evidence.delete(b.dataset.evidence):evidence.add(b.dataset.evidence);normalLab(l)});document.querySelectorAll('[data-option]').forEach(b=>b.onclick=()=>{const o=l.decision.options.find(x=>x.id===b.dataset.option);if(o.correct){set(key(l.id),'true');feedback='✓ '+o.feedback}else feedback='見直し：'+o.feedback;normalLab(l)});top()}
function reset(){evidence=new Set();feedback=''}
window.JAVA_APP={LABS,PREFIX,WAR_KEY,$,esc,get,set,key,done,top,home,normalLab,reset,needGrid,journey,lenses,completeBanner,openStack};
})();
