(function(){
const S=window.WARROOM_SCENARIOS||[];
const store={get(k){try{return localStorage.getItem(k)}catch(e){return null}},set(k,v){try{localStorage.setItem(k,v)}catch(e){}}};
let st=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function key(id){return 'financial_warroom_'+id+'_result'}
function getSaved(id){try{return JSON.parse(store.get(key(id))||'null')}catch(e){return null}}
function cls(n){return n>=85?'good':n>=70?'warn':'bad'}
function home(){
 st=null;let completed=S.filter(x=>getSaved(x.id)?.passed).length;
 let best={eng:0,con:0,pm:0};S.forEach(x=>{const r=getSaved(x.id);if(r){best.eng=Math.max(best.eng,r.eng||0);best.con=Math.max(best.con,r.con||0);best.pm=Math.max(best.pm,r.pm||0)}});
 document.getElementById('app').innerHTML=`<section class="hero"><div class="kicker">FINAL CAPSTONE / TRI-ROLE SIGN-OFF</div><h1>🚨 Financial War Room</h1><p class="muted">正解当てゲームではありません。<b>事実 → 仮説 → 証拠 → 影響/リスク判断 → rollback可能な復旧 → 技術＋金融データ検証 → 状況共有</b>の順番を守れるかを評価します。原因が当たっても、データを壊す復旧や説明責任を欠けば不合格です。</p><div class="chips"><span class="chip">12 Incidents</span><span class="chip">Evidence Budget</span><span class="chip">Engineer / Consultant / PM</span><span class="chip">85点×3でSign-off</span><span class="chip">${completed}/12 PASS</span></div></section>
 <section class="card"><h2>三者が見る合格条件</h2><div class="rolegrid"><div class="role engineer"><b>🧑‍💻 Financial Engineer</b><span class="muted">症状をレイヤ分解し、証拠で仮説を潰す。正本・commit・network path・control planeを混同しない。広範囲再起動よりreversible change。</span></div><div class="role consult"><b>🧭 Financial Consultant</b><span class="muted">顧客影響、重要業務、データ整合性、統制、外部委託/クラウド依存、RTO/RPO、残存リスクを意思決定へ翻訳する。</span></div><div class="role pm"><b>📋 PM / PMO</b><span class="muted">時間軸、担当、承認、rollback、依存関係、次回報告時刻を管理する。『原因未確定』を正しく伝えながら復旧を前へ進める。</span></div></div></section>
 <section class="card"><h2>Provider翻訳は最後にする</h2><div class="three"><div class="role"><b>AWS</b><span class="small">VPC / EC2 / RDS / IAM / KMS / CloudWatch / CloudTrail / Direct Connect</span></div><div class="role"><b>Google Cloud</b><span class="small">VPC / Compute / Cloud SQL / IAM / KMS / Monitoring / Audit Logs / Interconnect</span></div><div class="role"><b>Azure</b><span class="small">VNet / VM / Azure SQL / Entra/RBAC / Key Vault / Monitor / Activity Log / ExpressRoute</span></div></div><p class="muted">War Roomではまず「Network / Compute / Data / Identity / Observability / Hybrid / Batch」の共通レイヤで考え、そのあと各クラウドの製品名へ翻訳します。</p></section>
 <section class="card"><h2>Best Score</h2><div class="scorebox"><div class="score"><span>Engineer</span><b class="${cls(best.eng)}">${best.eng}</b></div><div class="score"><span>Consultant</span><b class="${cls(best.con)}">${best.con}</b></div><div class="score"><span>PM</span><b class="${cls(best.pm)}">${best.pm}</b></div><div class="score"><span>Passed</span><b>${completed}/12</b></div></div></section>
 <section class="card"><h2>Incidents</h2><div class="scenarioGrid">${S.map(x=>{const r=getSaved(x.id);return `<a class="scenario ${r?.passed?'complete':''}" href="#case${String(x.id).padStart(2,'0')}"><span class="done">✅ SIGN-OFF</span><div class="kicker">CASE ${String(x.id).padStart(2,'0')} / ${esc(x.severity)}</div><h3>${esc(x.title)}</h3><p class="muted">${esc(x.subtitle)}</p><div class="meta">${r?'E '+r.eng+' / C '+r.con+' / P '+r.pm:'未挑戦'}</div></a>`}).join('')}</div></section>
 <section class="card"><h2>Final Sign-off</h2><div class="rubric"><div><b>Engineer ≥ 85</b><div class="small">証拠・root cause・safe recovery・technical verification</div></div><div><b>Consultant ≥ 85</b><div class="small">重要業務・データ整合性・control/risk・trade-off</div></div><div><b>PM ≥ 85</b><div class="small">severity・timebox・approval/rollback・communication・checkpoint</div></div></div><p class="muted">3人すべて85点以上で、そのCaseに「三者Sign-off」が付きます。Final Case 12は、Core / Batch / Cloud ingest / reconciliationを横断する総合問題です。</p></section>`;
}
function start(sc){
 st={sc,time:30,scores:{eng:20,con:20,pm:20},impact:null,hyp:[],evidence:[],root:null,contrib:null,action:null,verify:[],comm:null,locked:{impact:false,root:false,action:false,verify:false,comm:false},log:["WAR ROOM OPEN: "+sc.title]};
 renderCase()
}
function renderCase(){
 const s=st.sc, f=s.facts;
 document.getElementById('app').innerHTML=`<section class="card incident"><div class="kicker">CASE ${String(s.id).padStart(2,'0')} / ${esc(s.severity)}</div><h1 style="font-size:clamp(28px,4vw,46px);margin:7px 0">${esc(s.title)}</h1><p>${esc(s.brief)}</p><div class="timer">⏱ Evidence budget: <span id="time">${st.time}</span> min</div><div class="facts">${Object.entries(f).map(([k,v])=>'<div class="fact"><div class="k">'+esc(k)+'</div><div class="v">'+esc(v)+'</div></div>').join('')}</div></section>
 <section class="card"><h2 class="sectionTitle">1. Business impact / Severity</h2><p class="muted">技術原因より先に、重要業務・顧客影響・締切を固定する。</p><div class="choices" id="impact">${s.impactOptions.map((x,i)=>'<button class="choice '+(st.impact===i?'selected':'')+'" data-impact="'+i+'">'+esc(x)+'</button>').join('')}</div><div class="feedback" id="impactFb"></div></section>
 <section class="card"><h2 class="sectionTitle">2. Hypothesis tree</h2><p class="muted">最大3つ。断定ではなく「確認すべき仮説」として置く。</p><div class="choices">${s.hypotheses.map(h=>'<button class="choice '+(st.hyp.includes(h[0])?'selected':'')+'" data-hyp="'+esc(h[0])+'">'+esc(h[1])+'</button>').join('')}</div></section>
 <section class="card"><h2 class="sectionTitle">3. Evidence request</h2><div class="two"><div class="choices">${s.evidence.map(e=>'<button class="evidenceBtn '+(st.evidence.includes(e.id)?'used':'')+'" data-ev="'+esc(e.id)+'" '+(st.evidence.includes(e.id)?'disabled':'')+'>'+esc(e.label)+' <span class="small">(-'+e.cost+'min)</span></button>').join('')}</div><div class="evidenceLog" id="elog">${esc(st.log.join('\n\n'))}</div></div></section>
 <section class="card"><h2 class="sectionTitle">4. Primary cause / Contributing factor</h2><div class="two"><div><div class="small">Primary cause</div><div class="choices">${s.hypotheses.map(h=>'<button class="choice '+(st.root===h[0]?'selected':'')+'" data-root="'+esc(h[0])+'">'+esc(h[1])+'</button>').join('')}</div></div><div><div class="small">Contributing factor</div><div class="choices">${s.hypotheses.concat([["design","設計/運用control不足"],["retry","retry/idempotency設計"],["routing","routing/monitoring設計"],["change","change/rehearsal不足"],["runbook","runbook/ownership不足"],["monitoring","監視/ownership不足"],["verification","end-to-end完了判定不足"],["governance","RPO/RTO逸脱時のgovernance"]]).map(h=>'<button class="choice '+(st.contrib===h[0]?'selected':'')+'" data-contrib="'+esc(h[0])+'">'+esc(h[1])+'</button>').join('')}</div></div></div><button class="nextBtn" id="lockRoot" ${st.locked.root?'disabled':''}>原因判断を確定</button><div class="feedback" id="rootFb"></div></section>
 <section class="card"><h2 class="sectionTitle">5. Recovery decision</h2><p class="muted">「直りそう」より、証拠・副作用・rollback・データ整合性で選ぶ。最初に選んだActionが評価対象。</p><div class="choices">${s.actions.map(a=>'<button class="actionBtn '+(st.action===a.id?(a.safe?'safe':'unsafe'):'')+'" data-action="'+esc(a.id)+'" '+(st.locked.action?'disabled':'')+'>'+esc(a.label)+'</button>').join('')}</div><div class="feedback" id="actionFb">${st.action?esc(s.actions.find(a=>a.id===st.action)?.effect):''}</div></section>
 <section class="card"><h2 class="sectionTitle">6. Verification / Reconciliation</h2><p class="muted">複数選択。技術SLIだけでなく、金融データ・顧客導線・後続処理まで見る。</p><div class="choices">${s.verifications.map(v=>'<button class="verifyBtn '+(st.verify.includes(v.id)?'selected':'')+'" data-ver="'+esc(v.id)+'" '+(st.locked.verify?'disabled':'')+'>'+esc(v.label)+'</button>').join('')}</div><button class="nextBtn" id="lockVerify" ${st.locked.verify?'disabled':''}>検証項目を確定</button></section>
 <section class="card"><h2 class="sectionTitle">7. Status communication</h2><p class="muted">原因未確定でも、事実・影響・未確定・次回更新時刻は共有できる。</p><div class="choices">${s.commsOptions.map((x,i)=>'<button class="choice '+(st.comm===i?'selected':'')+'" data-comm="'+i+'" '+(st.locked.comm?'disabled':'')+'>'+esc(x)+'</button>').join('')}</div><button class="nextBtn" id="finish">Score / Sign-off</button></section>
 <section class="card"><h2 class="sectionTitle">Live score</h2><div class="scorebox"><div class="score"><span>Engineer</span><b>${Math.round(st.scores.eng)}</b></div><div class="score"><span>Consultant</span><b>${Math.round(st.scores.con)}</b></div><div class="score"><span>PM</span><b>${Math.round(st.scores.pm)}</b></div><div class="score"><span>Time</span><b>${st.time}</b></div></div></section>`;
 bindCase()
}
function addPoints(p){for(const k of ['eng','con','pm'])st.scores[k]+=p[k]||0}
function bindCase(){
 document.querySelectorAll('[data-impact]').forEach(b=>b.onclick=()=>{if(st.locked.impact)return;st.impact=Number(b.dataset.impact);st.locked.impact=true;if(st.impact===st.sc.impactCorrect){st.scores.con+=10;st.scores.pm+=10} else {st.scores.con-=5;st.scores.pm-=7}renderCase()});
 document.querySelectorAll('[data-hyp]').forEach(b=>b.onclick=()=>{const id=b.dataset.hyp;if(st.hyp.includes(id))st.hyp=st.hyp.filter(x=>x!==id);else if(st.hyp.length<3)st.hyp.push(id);renderCase()});
 document.querySelectorAll('[data-ev]').forEach(b=>b.onclick=()=>{const e=st.sc.evidence.find(x=>x.id===b.dataset.ev);if(!e||st.evidence.includes(e.id))return;if(st.time<e.cost){alert('Evidence budget不足');return}st.time-=e.cost;st.evidence.push(e.id);addPoints(e.points);st.log.push('['+e.label+']\n'+e.text);renderCase()});
 document.querySelectorAll('[data-root]').forEach(b=>b.onclick=()=>{if(st.locked.root)return;st.root=b.dataset.root;renderCase()});
 document.querySelectorAll('[data-contrib]').forEach(b=>b.onclick=()=>{if(st.locked.root)return;st.contrib=b.dataset.contrib;renderCase()});
 const lr=document.getElementById('lockRoot');if(lr)lr.onclick=()=>{if(st.locked.root)return;st.locked.root=true;if(st.hyp.includes(st.sc.root))st.scores.eng+=10;if(st.hyp.includes(st.sc.contrib))st.scores.con+=5;if(st.root===st.sc.root){st.scores.eng+=15;st.scores.con+=8}else{st.scores.eng-=12;st.scores.con-=8}if(st.contrib===st.sc.contrib){st.scores.con+=10;st.scores.pm+=5}else{st.scores.con-=4}renderCase()};
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(st.locked.action)return;const a=st.sc.actions.find(x=>x.id===b.dataset.action);st.action=a.id;st.locked.action=true;const missing=(a.need||[]).filter(x=>!st.evidence.includes(x));addPoints(a.points);if(missing.length){st.scores.eng-=8;st.scores.pm-=5;st.log.push('RECOVERY NOTE: 必要証拠不足 '+missing.join(', '))}st.log.push('RECOVERY: '+a.label+'\n'+a.effect);renderCase()});
 document.querySelectorAll('[data-ver]').forEach(b=>b.onclick=()=>{if(st.locked.verify)return;const id=b.dataset.ver;if(st.verify.includes(id))st.verify=st.verify.filter(x=>x!==id);else st.verify.push(id);renderCase()});
 const lv=document.getElementById('lockVerify');if(lv)lv.onclick=()=>{if(st.locked.verify)return;st.locked.verify=true;st.verify.forEach(id=>{const v=st.sc.verifications.find(x=>x.id===id);if(v.correct)addPoints(v.points);else{st.scores.eng-=3;st.scores.con-=3;st.scores.pm-=2}});renderCase()};
 document.querySelectorAll('[data-comm]').forEach(b=>b.onclick=()=>{if(st.locked.comm)return;st.comm=Number(b.dataset.comm);st.locked.comm=true;if(st.comm===st.sc.commCorrect){st.scores.con+=8;st.scores.pm+=15}else{st.scores.con-=7;st.scores.pm-=12}renderCase()});
 document.getElementById('finish').onclick=finish
}
function finish(){
 if(st.root===null||st.action===null||!st.locked.verify||st.comm===null){alert('原因判断・Recovery・Verification・Communicationまで確定してから採点します。');return}
 const over=Math.max(0,st.evidence.length-4);const low=Math.max(0,10-st.time);
 st.scores.eng-=over*3+low*0.5;st.scores.pm-=over*4+low;st.scores.con-=over*1.5;
 for(const k of ['eng','con','pm'])st.scores[k]=Math.max(0,Math.min(100,Math.round(st.scores[k])));
 const passed=st.scores.eng>=85&&st.scores.con>=85&&st.scores.pm>=85;
 const result={...st.scores,passed,time:st.time,date:new Date().toISOString()};store.set(key(st.sc.id),JSON.stringify(result));
 document.getElementById('app').innerHTML=`<section class="card result"><div class="kicker">CASE ${String(st.sc.id).padStart(2,'0')} RESULT</div><h1 style="font-size:40px;margin:8px 0">${passed?'✅ TRI-ROLE SIGN-OFF':'🟡 REVIEW REQUIRED'}</h1><p class="muted">${esc(st.sc.rootExplain)}</p><div class="scorebox"><div class="score"><span>Engineer</span><b class="${cls(st.scores.eng)}">${st.scores.eng}</b></div><div class="score"><span>Consultant</span><b class="${cls(st.scores.con)}">${st.scores.con}</b></div><div class="score"><span>PM</span><b class="${cls(st.scores.pm)}">${st.scores.pm}</b></div><div class="score"><span>Evidence time</span><b>${30-st.time}m</b></div></div><p class="signoff ${passed?'good':'warn'}">${passed?'敏腕3者の合格ラインを満たしました。':'85点未満の視点があります。Evidenceを取りすぎず、業務影響・safe recovery・金融データ検証を見直そう。'}</p><div class="two"><button class="nextBtn" id="retry">↻ Retry Case</button><button class="nextBtn" id="home">⌂ War Room Home</button></div></section>
 <section class="card"><h2>評価ロジック</h2><div class="rubric"><div><b>Engineer</b><div class="small">高価値Evidence / root cause / 必要証拠を揃えたreversible recovery / technical validation</div></div><div><b>Consultant</b><div class="small">severity / data integrity / contributing control / business & risk verification</div></div><div><b>PM</b><div class="small">timebox / evidence efficiency / approval・rollback / status communication / downstream checkpoint</div></div></div></section>`;
 document.getElementById('retry').onclick=()=>start(st.sc);document.getElementById('home').onclick=()=>{location.hash='#home'}
}
function route(){const m=location.hash.match(/^#case(\d{1,2})$/);if(m){const s=S.find(x=>x.id===Number(m[1]));if(s)start(s);else home()}else home()}
window.addEventListener('hashchange',route);if(!location.hash)location.hash='#home';route()
})();
