(function(){
'use strict';
const S=window.WARROOM_SCENARIOS||[];
const G=window.WARROOM_BEGINNER_GUIDE||{glossary:[],flow:[],cases:{}};
const store={get(k){try{return localStorage.getItem(k)}catch(e){return null}},set(k,v){try{localStorage.setItem(k,v)}catch(e){}}};
let st=null;
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function key(id){return 'financial_warroom_'+id+'_result'}
function getSaved(id){try{return JSON.parse(store.get(key(id))||'null')}catch(e){return null}}
function cls(n){return n>=85?'good':n>=70?'warn':'bad'}
function caseGuide(sc){return G.cases?.[sc.id]||{layer:'🧭 End-to-End',plain:sc.subtitle,focus:'何が正常で、何が異常で、何がまだ分からないかを分ける。',facts:Object.entries(sc.facts||{}),map:'Customer → System → Data\n\n❓ どこに問題があるかは未確定'}}
function sevText(s){return s==='SEV1'?'重大：重要業務・顧客・決済などへの大きな影響を想定':s==='SEV2'?'中〜大：重要業務の一部劣化・限定的な顧客影響を想定':'小：主に内部影響。顧客影響は限定的またはなし'}
const FACT_LABELS={customer:'顧客影響',transfer:'振込',LB:'入口 / LB','recent change':'直近変更',write:'書き込み',read:'読み取り',scope:'影響範囲',network:'Network',API:'API',ledger:'元帳 / Ledger',cloud:'Cloud','core call':'Core呼出し',static:'Cloud内処理',hybrid:'Hybrid接続',credential:'Credential',auth:'認証',certificate:'証明書',TLS:'TLS','new env':'新環境','old env':'旧環境',TTL:'TTL',cutover:'切替時刻',JCL:'JCL',processed:'処理件数',commit:'Commit',deadline:'締切',accept:'受付',reflect:'反映',queue:'Queue',consumer:'Consumer','403':'403影響',attack:'攻撃通信',change:'直近変更',backend:'Backend',region:'Region',DR:'DR',RPO:'RPO',RTO:'RTO',export:'Export',ingest:'Cloud取込'};
function factLabel(k){return FACT_LABELS[k]||String(k).replace(/_/g,' ')}
function factValue(v){return String(v).replace(/^normal$/i,'正常').replace(/^healthy$/i,'正常').replace(/^success$/i,'成功').replace(/^running$/i,'稼働中').replace(/^no change$/i,'変更なし').replace(/^unrelated$/i,'今回とは無関係').replace(/^up$/i,'接続中')}
function flowStrip(active=0){return `<div class="wrFlow">${(G.flow||[]).map((x,i)=>`<div class="wrFlowStep ${active===i+1?'active':''} ${active>i+1?'done':''}"><span>${esc(x[0])}</span><b>${esc(x[1])}</b><small>${esc(x[2])}</small></div>`).join('')}</div>`}
function glossary(){return `<details class="wrGlossary"><summary>📖 初めてなら、この5語だけ確認</summary><div class="wrGlossaryGrid">${(G.glossary||[]).map(x=>`<div><b>${esc(x[0])}</b><span>${esc(x[1])}</span></div>`).join('')}</div></details>`}
function sectionTitle(n,ja,en,help){return `<h2 class="sectionTitle"><span class="wrSectionNo">${n}</span>${ja}<small>${en}</small></h2>${help?`<p class="muted wrSectionHelp">${help}</p>`:''}`}
function currentPhase(){if(!st)return 0;if(st.impact===null)return 1;if(st.hyp.length===0)return 2;if(st.evidence.length===0)return 3;if(!st.locked.root)return 4;if(st.action===null)return 5;if(!st.locked.verify)return 6;return 7}
function home(){
 st=null;let completed=S.filter(x=>getSaved(x.id)?.passed).length;
 let best={eng:0,con:0,pm:0};S.forEach(x=>{const r=getSaved(x.id);if(r){best.eng=Math.max(best.eng,r.eng||0);best.con=Math.max(best.con,r.con||0);best.pm=Math.max(best.pm,r.pm||0)}});
 document.getElementById('app').innerHTML=`
 <section class="hero wrHero"><div class="kicker">FINAL CAPSTONE / FINANCIAL INCIDENT SIMULATOR</div><h1>🚨 Financial War Room</h1><p class="wrHeroLead">銀行システムで障害が起きた。<b>あなたは対応会議に呼ばれました。</b></p><p class="muted">原因はまだ分かりません。限られた時間で「何が止まっている？ → 何を確認する？ → どう安全に戻す？ → 本当に業務は戻った？」を順番に判断する教材です。最初から専門用語を知っている必要はありません。</p><div class="chips"><span class="chip">12 Cases</span><span class="chip">まず状況を見る</span><span class="chip">証拠で判断</span><span class="chip">安全に復旧</span><span class="chip">${completed}/12 SIGN-OFF</span></div></section>
 <section class="card wrIntro"><div class="wrIntroTop"><div><div class="kicker">30秒で分かる</div><h2>War Roomで、あなたは何をするの？</h2></div><div class="wrRolePlain">👥 エンジニアだけの試験ではない</div></div><p class="muted">障害対応では、技術原因だけ分かっても足りません。顧客影響、データ、復旧の副作用、締切、関係者への共有まで含めて「安全に前へ進める」ことがゴールです。</p>${flowStrip(0)}${glossary()}</section>
 <section class="card wrCases"><div class="wrCasesHead"><div><div class="kicker">CHOOSE AN INCIDENT</div><h2>まずはCaseを覗いてみる</h2></div><span class="small">初めてなら Case 01 推奨</span></div><div class="scenarioGrid">${S.map(x=>{const r=getSaved(x.id),g=caseGuide(x);return `<a class="scenario ${r?.passed?'complete':''}" href="#preview${String(x.id).padStart(2,'0')}"><span class="done">✅ SIGN-OFF</span><div class="kicker">CASE ${String(x.id).padStart(2,'0')} / ${esc(x.severity)}</div><div class="wrLayerChip">${esc(g.layer)}</div><h3>${esc(x.subtitle)}</h3><div class="wrEnglishTitle">${esc(x.title)}</div><p class="wrCasePlain">${esc(g.plain)}</p><div class="meta">${r?'E '+r.eng+' / C '+r.con+' / P '+r.pm:'状況を見る →'}</div></a>`}).join('')}</div></section>
 <details class="card wrAdvanced"><summary>🧠 採点・3役・Providerなど詳しい設計を見る</summary><div class="wrAdvancedBody">
 <section><h2>三者が見る合格条件</h2><div class="rolegrid"><div class="role engineer"><b>🧑‍💻 Financial Engineer</b><span class="muted">症状をレイヤ分解し、証拠で仮説を潰す。広範囲再起動よりreversible change。</span></div><div class="role consult"><b>🧭 Financial Consultant</b><span class="muted">顧客影響、重要業務、データ整合性、統制、RTO/RPO、残存リスクへ翻訳する。</span></div><div class="role pm"><b>📋 PM / PMO</b><span class="muted">時間軸、担当、承認、rollback、依存関係、次回報告時刻を管理する。</span></div></div></section>
 <section><h2>Provider翻訳は最後</h2><div class="three"><div class="role"><b>AWS</b><span class="small">VPC / EC2 / RDS / IAM / CloudWatch...</span></div><div class="role"><b>Google Cloud</b><span class="small">VPC / Compute / Cloud SQL / IAM / Monitoring...</span></div><div class="role"><b>Azure</b><span class="small">VNet / VM / Azure SQL / Entra/RBAC / Monitor...</span></div></div><p class="muted">まず Network / Compute / Data / Identity / Hybrid / Batch など共通レイヤで考え、そのあと製品名へ翻訳します。</p></section>
 <section><h2>Best Score</h2><div class="scorebox"><div class="score"><span>Engineer</span><b class="${cls(best.eng)}">${best.eng}</b></div><div class="score"><span>Consultant</span><b class="${cls(best.con)}">${best.con}</b></div><div class="score"><span>PM</span><b class="${cls(best.pm)}">${best.pm}</b></div><div class="score"><span>Passed</span><b>${completed}/12</b></div></div></section>
 <section><h2>Final Sign-off</h2><p class="muted">各Caseで Engineer / Consultant / PM がすべて85点以上ならSign-off。Case12が最終総合問題です。</p></section>
 </div></details>`;
}
function preview(sc){
 st=null;const g=caseGuide(sc),facts=Array.isArray(g.facts)?g.facts:Object.entries(sc.facts||{});
 document.getElementById('app').innerHTML=`
 <section class="card wrPreviewHero"><div class="wrPreviewNav"><a href="#home">← Casesへ</a><span>初見ガイド / まだ採点されません</span></div><div class="kicker">CASE ${String(sc.id).padStart(2,'0')} / ${esc(sc.severity)}</div><h1>${esc(sc.subtitle)}</h1><div class="wrEnglishTitle wrPreviewEnglish">${esc(sc.title)}</div><p class="wrPreviewPlain">${esc(g.plain)}</p><div class="wrSeverity"><b>${esc(sc.severity)}</b><span>${esc(sevText(sc.severity))}</span></div></section>
 <section class="wrPreviewGrid"><div class="card"><div class="kicker">SYSTEM POSITION</div><h2>何が起きているの？</h2><pre class="wrSystemMap">${esc(g.map)}</pre><div class="wrFocus"><b>👀 このCaseで見るポイント</b><span>${esc(g.focus)}</span></div></div><div class="card"><div class="kicker">KNOWN FACTS</div><h2>今わかっていること</h2><div class="facts wrPreviewFacts">${facts.map(([k,v])=>`<div class="fact"><div class="k">${esc(k)}</div><div class="v">${esc(v)}</div></div>`).join('')}</div><div class="wrUnknown"><b>❓ まだ分からない</b><span>原因はまだ確定していません。この時点で「Cloud障害」「DB障害」などと決めつけないのがWar Roomのスタートです。</span></div></div></section>
 <section class="card wrBeforeStart"><div class="kicker">WHAT YOU WILL DO</div><h2>このあと、何をすればいい？</h2>${flowStrip(0)}<div class="wrPreviewActions"><a class="wrPrimary" href="#case${String(sc.id).padStart(2,'0')}">状況は分かった → 挑戦を始める</a><a class="wrSecondary" href="#home">別のCaseを見る</a></div>${glossary()}</section>`;
}
function start(sc){
 st={sc,time:30,scores:{eng:20,con:20,pm:20},impact:null,hyp:[],evidence:[],root:null,contrib:null,action:null,verify:[],comm:null,locked:{impact:false,root:false,action:false,verify:false,comm:false},log:["WAR ROOM OPEN: "+sc.title]};
 renderCase()
}
function renderCase(){
 const s=st.sc,f=s.facts,phase=currentPhase();
 document.getElementById('app').innerHTML=`
 <section class="card incident"><div class="wrChallengeTop"><a href="#preview${String(s.id).padStart(2,'0')}">← 初見ガイドへ戻る</a><span>CHALLENGE MODE / 採点中</span></div><div class="kicker">CASE ${String(s.id).padStart(2,'0')} / ${esc(s.severity)}</div><h1 style="font-size:clamp(28px,4vw,46px);margin:7px 0">${esc(s.title)}</h1><p>${esc(s.brief)}</p><div class="timer">⏱ 残り確認時間: <span id="time">${st.time}</span> min</div><p class="small wrBudgetHelp">Evidence（確認材料）を見るたびに時間を使います。全部見るのではなく「この仮説を確認するには何が必要？」で選びます。</p><div class="facts">${Object.entries(f).map(([k,v])=>`<div class="fact"><div class="k">${esc(factLabel(k))}</div><div class="v">${esc(factValue(v))}</div></div>`).join('')}</div>${flowStrip(phase)}</section>
 <section class="card">${sectionTitle('1','まず「どれくらい困っているか」を決める','Business impact / Severity','技術原因より先に、重要業務・顧客影響・締切を固定します。')}<div class="choices" id="impact">${s.impactOptions.map((x,i)=>'<button class="choice '+(st.impact===i?'selected':'')+'" data-impact="'+i+'">'+esc(x)+'</button>').join('')}</div><div class="feedback" id="impactFb"></div></section>
 <section class="card">${sectionTitle('2','原因の候補を置く','Hypothesis tree','まだ原因を当てる場面ではありません。「あり得る候補」を最大3つ置きます。')}<div class="choices">${s.hypotheses.map(h=>'<button class="choice '+(st.hyp.includes(h[0])?'selected':'')+'" data-hyp="'+esc(h[0])+'">'+esc(h[1])+'</button>').join('')}</div></section>
 <section class="card">${sectionTitle('3','確認材料を取りに行く','Evidence request','選んだEvidenceで、どの仮説が残る／消えるのかを考えます。')}<div class="two"><div class="choices">${s.evidence.map(e=>'<button class="evidenceBtn '+(st.evidence.includes(e.id)?'used':'')+'" data-ev="'+esc(e.id)+'" '+(st.evidence.includes(e.id)?'disabled':'')+'>'+esc(e.label)+' <span class="small">(-'+e.cost+'min)</span></button>').join('')}</div><div class="evidenceLog" id="elog">${esc(st.log.join('\n\n'))}</div></div></section>
 <section class="card">${sectionTitle('4','集めた証拠から原因を判断する','Primary cause / Contributing factor','直接の主原因と、「なぜ起きやすかった／拡大したか」という背景要因を分けます。')}<div class="two"><div><div class="small">Primary cause / 主原因</div><div class="choices">${s.hypotheses.map(h=>'<button class="choice '+(st.root===h[0]?'selected':'')+'" data-root="'+esc(h[0])+'">'+esc(h[1])+'</button>').join('')}</div></div><div><div class="small">Contributing factor / 背景要因</div><div class="choices">${s.hypotheses.concat([["design","設計/運用control不足"],["retry","retry/idempotency設計"],["routing","routing/monitoring設計"],["change","change/rehearsal不足"],["runbook","runbook/ownership不足"],["monitoring","監視/ownership不足"],["verification","end-to-end完了判定不足"],["governance","RPO/RTO逸脱時のgovernance"]]).map(h=>'<button class="choice '+(st.contrib===h[0]?'selected':'')+'" data-contrib="'+esc(h[0])+'">'+esc(h[1])+'</button>').join('')}</div></div></div><button class="nextBtn" id="lockRoot" ${st.locked.root?'disabled':''}>原因判断を確定</button><div class="feedback" id="rootFb"></div></section>
 <section class="card">${sectionTitle('5','安全な戻し方を選ぶ','Recovery decision','「直りそう」だけでなく、副作用・rollback・データ整合性を見て選びます。最初のActionが評価対象です。')}<div class="choices">${s.actions.map(a=>'<button class="actionBtn '+(st.action===a.id?(a.safe?'safe':'unsafe'):'')+'" data-action="'+esc(a.id)+'" '+(st.locked.action?'disabled':'')+'>'+esc(a.label)+'</button>').join('')}</div><div class="feedback" id="actionFb">${st.action?esc(s.actions.find(a=>a.id===st.action)?.effect):''}</div></section>
 <section class="card">${sectionTitle('6','本当に業務が戻ったか確認する','Verification / Reconciliation','技術メトリクスだけでなく、顧客導線・件数・金額・後続処理まで見ます。')}<div class="choices">${s.verifications.map(v=>'<button class="verifyBtn '+(st.verify.includes(v.id)?'selected':'')+'" data-ver="'+esc(v.id)+'" '+(st.locked.verify?'disabled':'')+'>'+esc(v.label)+'</button>').join('')}</div><button class="nextBtn" id="lockVerify" ${st.locked.verify?'disabled':''}>検証項目を確定</button></section>
 <section class="card">${sectionTitle('7','関係者へ今の状況を共有する','Status communication','原因未確定でも、事実・影響・未確定・次Action・次回更新時刻は伝えられます。')}<div class="choices">${s.commsOptions.map((x,i)=>'<button class="choice '+(st.comm===i?'selected':'')+'" data-comm="'+i+'" '+(st.locked.comm?'disabled':'')+'>'+esc(x)+'</button>').join('')}</div><button class="nextBtn" id="finish">Score / Sign-off</button></section>
 <details class="card wrLiveScore"><summary>📊 現在の採点状況を見る</summary><div class="scorebox"><div class="score"><span>Engineer</span><b>${Math.round(st.scores.eng)}</b></div><div class="score"><span>Consultant</span><b>${Math.round(st.scores.con)}</b></div><div class="score"><span>PM</span><b>${Math.round(st.scores.pm)}</b></div><div class="score"><span>Time</span><b>${st.time}</b></div></div></details>`;
 bindCase()
}
function addPoints(p){for(const k of ['eng','con','pm'])st.scores[k]+=p[k]||0}
function bindCase(){
 document.querySelectorAll('[data-impact]').forEach(b=>b.onclick=()=>{if(st.locked.impact)return;st.impact=Number(b.dataset.impact);st.locked.impact=true;if(st.impact===st.sc.impactCorrect){st.scores.con+=10;st.scores.pm+=10}else{st.scores.con-=5;st.scores.pm-=7}renderCase()});
 document.querySelectorAll('[data-hyp]').forEach(b=>b.onclick=()=>{const id=b.dataset.hyp;if(st.hyp.includes(id))st.hyp=st.hyp.filter(x=>x!==id);else if(st.hyp.length<3)st.hyp.push(id);renderCase()});
 document.querySelectorAll('[data-ev]').forEach(b=>b.onclick=()=>{const e=st.sc.evidence.find(x=>x.id===b.dataset.ev);if(!e||st.evidence.includes(e.id))return;if(st.time<e.cost){alert('Evidence budget不足');return}st.time-=e.cost;st.evidence.push(e.id);addPoints(e.points);st.log.push('['+e.label+']\n'+e.text);renderCase()});
 document.querySelectorAll('[data-root]').forEach(b=>b.onclick=()=>{if(st.locked.root)return;st.root=b.dataset.root;renderCase()});
 document.querySelectorAll('[data-contrib]').forEach(b=>b.onclick=()=>{if(st.locked.root)return;st.contrib=b.dataset.contrib;renderCase()});
 const lr=document.getElementById('lockRoot');if(lr)lr.onclick=()=>{if(st.locked.root)return;st.locked.root=true;if(st.hyp.includes(st.sc.root))st.scores.eng+=10;if(st.hyp.includes(st.sc.contrib))st.scores.con+=5;if(st.root===st.sc.root){st.scores.eng+=15;st.scores.con+=8}else{st.scores.eng-=12;st.scores.con-=8}if(st.contrib===st.sc.contrib){st.scores.con+=10;st.scores.pm+=5}else{st.scores.con-=4}renderCase()};
 document.querySelectorAll('[data-action]').forEach(b=>b.onclick=()=>{if(st.locked.action)return;const a=st.sc.actions.find(x=>x.id===b.dataset.action);st.action=a.id;st.locked.action=true;const missing=(a.need||[]).filter(x=>!st.evidence.includes(x));addPoints(a.points);if(missing.length){st.scores.eng-=8;st.scores.pm-=5;st.log.push('RECOVERY NOTE: 必要証拠不足 '+missing.join(', '))}st.log.push('RECOVERY: '+a.label+'\n'+a.effect);renderCase()});
 document.querySelectorAll('[data-ver]').forEach(b=>b.onclick=()=>{if(st.locked.verify)return;const id=b.dataset.ver;if(st.verify.includes(id))st.verify=st.verify.filter(x=>x!==id);else st.verify.push(id);renderCase()});
 const lv=document.getElementById('lockVerify');if(lv)lv.onclick=()=>{if(st.locked.verify)return;st.locked.verify=true;st.verify.forEach(id=>{const v=st.sc.verifications.find(x=>x.id===id);if(v.correct)addPoints(v.points);else{st.scores.eng-=3;st.scores.con-=3;st.scores.pm-=2}});renderCase()};
 document.querySelectorAll('[data-comm]').forEach(b=>b.onclick=()=>{if(st.locked.comm)return;st.comm=Number(b.dataset.comm);st.locked.comm=true;if(st.comm===st.sc.commCorrect){st.scores.con+=8;st.scores.pm+=15}else{st.scores.con-=7;st.scores.pm-=12}renderCase()});
 document.getElementById('finish').onclick=finish
}
function finish(){
 if(st.root===null||st.action===null||!st.locked.verify||st.comm===null){alert('原因判断・Recovery・Verification・Communicationまで確定してから採点します。');return}
 const over=Math.max(0,st.evidence.length-4),low=Math.max(0,10-st.time);
 st.scores.eng-=over*3+low*0.5;st.scores.pm-=over*4+low;st.scores.con-=over*1.5;
 for(const k of ['eng','con','pm'])st.scores[k]=Math.max(0,Math.min(100,Math.round(st.scores[k])));
 const passed=st.scores.eng>=85&&st.scores.con>=85&&st.scores.pm>=85;
 const result={...st.scores,passed,time:st.time,date:new Date().toISOString()};store.set(key(st.sc.id),JSON.stringify(result));
 document.getElementById('app').innerHTML=`<section class="card result"><div class="kicker">CASE ${String(st.sc.id).padStart(2,'0')} RESULT</div><h1 style="font-size:40px;margin:8px 0">${passed?'✅ TRI-ROLE SIGN-OFF':'🟡 REVIEW REQUIRED'}</h1><p class="muted">${esc(st.sc.rootExplain)}</p><div class="scorebox"><div class="score"><span>Engineer</span><b class="${cls(st.scores.eng)}">${st.scores.eng}</b></div><div class="score"><span>Consultant</span><b class="${cls(st.scores.con)}">${st.scores.con}</b></div><div class="score"><span>PM</span><b class="${cls(st.scores.pm)}">${st.scores.pm}</b></div><div class="score"><span>Evidence time</span><b>${30-st.time}m</b></div></div><p class="signoff ${passed?'good':'warn'}">${passed?'3つの視点すべてで合格ラインを満たしました。':'85点未満の視点があります。Evidenceの選び方、業務影響、安全な復旧、金融データ検証を見直そう。'}</p><div class="two"><button class="nextBtn" id="retry">↻ Retry Case</button><button class="nextBtn" id="home">⌂ War Room Home</button></div></section><section class="card"><h2>今回の答え合わせ</h2><p class="muted">${esc(st.sc.rootExplain)}</p><div class="rubric"><div><b>Engineer</b><div class="small">Evidence / root cause / reversible recovery / technical validation</div></div><div><b>Consultant</b><div class="small">severity / data integrity / control / business & risk verification</div></div><div><b>PM</b><div class="small">timebox / approval・rollback / communication / checkpoint</div></div></div></section>`;
 document.getElementById('retry').onclick=()=>start(st.sc);document.getElementById('home').onclick=()=>{location.hash='#home'}
}
function route(){
 const p=location.hash.match(/^#preview(\d{1,2})$/i);if(p){const s=S.find(x=>x.id===Number(p[1]));if(s){preview(s);return}}
 const m=location.hash.match(/^#case(\d{1,2})$/i);if(m){const s=S.find(x=>x.id===Number(m[1]));if(s){start(s);return}}
 home()
}
window.addEventListener('hashchange',route);if(!location.hash)location.hash='#home';route()
})();
