(function(){
'use strict';
function addParent(){if(document.querySelector('.fit-linux-parent'))return;var a=document.createElement('a');a.className='fit-linux-parent';a.href='../';a.textContent='⌂ Financial IT TOP';a.style.cssText='position:fixed;left:10px;bottom:10px;z-index:9995;text-decoration:none;border:1px solid #38516e;border-radius:999px;background:#101c2f;color:#dce8f4;padding:9px 12px;font:750 12px system-ui,-apple-system,Segoe UI,sans-serif;box-shadow:0 10px 30px rgba(0,0,0,.28)';document.body.appendChild(a)}
function loadPackage(){if(document.querySelector('script[data-fit-package]'))return;var s=document.createElement('script');s.src='../assets/js/module-package.js?v=2';s.dataset.fitPackage='1';document.body.appendChild(s)}
function loadFinancialProfiles(){if(document.querySelector('script[data-financial-linux-profiles]'))return;var s=document.createElement('script');s.src='./ui-financial-profiles.js?v=1';s.dataset.financialLinuxProfiles='1';document.body.appendChild(s)}
function loadFoundationGlossary(){if(document.querySelector('script[data-foundation-glossary]'))return;var s=document.createElement('script');s.src='../assets/js/foundation-glossary.js?v=1';s.dataset.foundationGlossary='1';document.body.appendChild(s)}
function loadComponentRationale(){var old=document.querySelector('script[data-component-rationale]');if(old){loadFoundationGlossary();loadFinancialProfiles();return}var s=document.createElement('script');s.src='../assets/js/component-rationale.js?v=2';s.dataset.componentRationale='1';s.onload=function(){loadFoundationGlossary();loadFinancialProfiles()};document.body.appendChild(s)}
function loadFieldLinks(){if(document.querySelector('script[data-fit-field-links]'))return;var s=document.createElement('script');s.src='../assets/js/field-case-links.js?v=1';s.dataset.fitFieldLinks='1';document.body.appendChild(s)}
function addZero(){if(!/\/linux\/?(?:index\.html)?$/i.test(location.pathname)||document.querySelector('.fit-linux-zero'))return;var hero=document.querySelector('.hero');if(!hero)return;var sec=document.createElement('section');sec.className='fit-linux-zero';sec.style.cssText='margin-top:12px;padding:15px;border:1px solid #355c78;border-radius:15px;background:linear-gradient(135deg,#102d25,#111b2d);color:#e8edf7';sec.innerHTML='<div style="font:900 12px ui-monospace,monospace;color:#76e3b2">START FROM ZERO / v19 FOUNDATION MODEL</div><h2 style="margin:5px 0 8px">普通の言葉から、Computer・OS・Linuxへ</h2><div style="display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:6px;font-size:12px;text-align:center"><div>💻 Computer</div><div>🧠 OS / Kernel</div><div>🌐 Network</div><div>⚙ Service / Process</div><div>🧾 Log / Evidence</div></div><p style="margin:9px 0 0;color:#aab8c9;line-height:1.6">STEP -2でCPU・Memory・Kernel・Process・File・Default Route等を役割から理解し、STEP -1でRHEL系を教材標準にUbuntu LTS・SLES・Oracle Linuxへ翻訳します。</p>';hero.insertAdjacentElement('afterend',sec);var style=document.createElement('style');style.textContent='@media(max-width:680px){.fit-linux-zero>div:nth-of-type(2){grid-template-columns:1fr!important;text-align:left!important}}';document.head.appendChild(style)}
addParent();addZero();loadPackage();loadComponentRationale();loadFieldLinks();
})();
