const GROUPS=['基礎','変更・整合性','金融実務'];
const store={get(k){try{return localStorage.getItem(k)}catch(e){return null}},set(k,v){try{localStorage.setItem(k,v)}catch(e){}}};
let runtime=null;
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function key(id){return 'sql_db_lab'+String(id).padStart(2,'0')+'_complete'}
function hash(id){return '#lab'+String(id).padStart(2,'0')}
function curLab(){const m=location.hash.match(/^#lab(\d{1,2})$/i);return m?LABS.find(x=>x.id===Number(m[1])):null}
function topNav(lab){const n=document.getElementById('topNav');if(!lab){n.innerHTML='<a href="#home">20 Labs</a><span>金融DB学習シミュレーター</span>';return}const p=LABS.find(x=>x.id===lab.id-1),q=LABS.find(x=>x.id===lab.id+1);n.innerHTML='<a href="#home">⌂ Labs</a>'+(p?'<a href="'+hash(p.id)+'">← Lab '+String(p.id).padStart(2,'0')+'</a>':'')+(q?'<a href="'+hash(q.id)+'">Lab '+String(q.id).padStart(2,'0')+' →</a>':'')}
function home(){runtime=null;topNav(null);let done=LABS.filter(x=>store.get(key(x.id))==='true').length;let groups=GROUPS.map(g=>{let cards=LABS.filter(x=>x.group===g).map(x=>'<a class="labcard '+(store.get(key(x.id))==='true'?'complete':'')+'" href="'+hash(x.id)+'"><span class="done">✅</span><div class="num">LAB '+String(x.id).padStart(2,'0')+'</div><h3>'+esc(x.title)+'</h3><div class="desc">'+esc(x.subtitle)+'</div></a>').join('');return '<section class="group"><h2>'+esc(g)+'</h2><div class="labgrid">'+cards+'</div></section>'}).join('');
document.getElementById('app').innerHTML=`<section class="card hero"><div class="heroGrid"><div><div class="kicker">FINANCIAL SQL / DATABASE LAB 01–20</div><h1>金融データを、<br>壊さず・迷わず・説明できる。</h1><p class="muted">目標はSQL暗記ではありません。顧客・口座・取引データを<strong>探す → 結ぶ → 集計する → 安全に更新する → 競合を切り分ける → 照合して説明する</strong>20 Labsです。</p><div class="chips"><span class="chip">SELECT / JOIN</span><span class="chip">Transaction</span><span class="chip">Lock / Isolation</span><span class="chip">Db2 / COBOL</span><span class="chip">War Room</span></div></div><div class="goal"><strong>修了ライン</strong><div>「残高が合わない」に対して、いきなりUPDATEせず、どの表・取引・ロック・監査を確認するかを証拠付きで説明できる。</div><div class="progress"><div style="width:${done/20*100}%"></div></div><div class="summary"><span class="pill"><b>${done}</b> / 20 COMPLETE</span><span class="pill">最終: Balance War Room</span></div></div></div></section>
<section class="card stage0" id="stage0"><div class="stage0top"><div><div class="kicker">LEARNING STEP 0</div><h2 style="font-size:24px;margin-top:4px">SQL / Databaseって、そもそも何をするの？</h2><p class="muted" style="margin-bottom:0">ATMやアプリが「残高を見せて」と頼むと、DBMSがデータを探し、SQLで指定した結果を返します。まず1回、処理の流れを動かしてみよう。</p></div><a class="startBtn" href="#lab01">Lab01へ →</a></div><div class="stage0Grid"><div><div class="flow0"><div class="node0" id="s0n0"><b>📱 App / ATM</b><span>残高照会</span></div><div class="node0" id="s0n1"><b>🧾 SQL</b><span>何を探すか指定</span></div><div class="node0" id="s0n2"><b>⚙ DBMS</b><span>検索・整合性管理</span></div><div class="node0" id="s0n3"><b>🗃 Table</b><span>ACCOUNTから1行</span></div><div class="node0" id="s0n4"><b>✅ Result</b><span>残高100,000円</span></div></div><div class="stage0Btns"><button onclick="stage0(0)">① 照会を送る</button><button onclick="stage0(1)">② SQLを見る</button><button onclick="stage0(2)">③ DBで検索</button><button onclick="stage0(4)">④ 結果を返す</button></div><div class="stage0Console" id="s0console">まだ何もしていません。①から押してみよう。</div></div><div class="roles"><div class="role"><b>SQL</b><small>DBへ「どのデータを、どう取得・更新するか」を伝える言語。</small></div><div class="role"><b>Database</b><small>顧客・口座・取引などのデータをルール付きで保存する仕組み。</small></div><div class="role"><b>DBMS（Db2 / Oracle / PostgreSQLなど）</b><small>SQLを解釈し、データ・トランザクション・ロックなどを管理するソフトウェア。</small></div><div class="role"><b>COBOL / Java / API</b><small>業務処理を担当するアプリ側。COBOLからDb2へEXEC SQLする構成もある。</small></div><div class="role"><b>大事な区別</b><small><b>SQL ≠ Database ≠ DBMS</b>。SQLは言語、DBはデータの集合/仕組み、DBMSはそれを管理するソフト。</small></div></div></div></section>
${groups}<section class="card outcome"><h2>修了時の到達像</h2><div class="layers"><span>Table / Row / Column</span><span>SELECT / WHERE</span><span>Aggregate / JOIN</span><span>NULL / Constraint</span><span>INSERT / UPDATE</span><span>COMMIT / ROLLBACK</span><span>Lock / Isolation</span><span>Index / EXPLAIN</span><span>Reconciliation</span><span>Db2 / COBOL</span><span>Security / Audit</span></div><p class="muted">技術者になりきることではなく、金融ITの会議で「どのデータが正か」「更新は確定済みか」「ロック待ちか」「件数/金額は一致したか」を具体的に確認できる状態を狙います。</p></section><p class="footer">※ 学習用シミュレーターです。SQL構文・ロック・権限・監視方法はDBMSやシステム構成で異なります。本番環境では所属組織の変更管理・権限・承認・Runbookに従ってください。</p>`}
function stage0(i){document.querySelectorAll('.node0').forEach((e,n)=>e.classList.toggle('on',n<=i));let t=["📱 残高照会リクエスト\naccount_id = 00192837\n\nまだDBへは触っていません。","🧾 アプリがDBへ問い合わせ\n\nSELECT balance\nFROM account\nWHERE account_id = '00192837';\n\nSQL = 『何を、どこから、どの条件で』","⚙ DBMSがSQLを解釈\n→ ACCOUNT表を検索\n→ account_id=00192837 を特定\n→ 1行のBALANCEを読む","🗃 ACCOUNT\n00192837 | C0001 | 100000 | ACTIVE","✅ Query result\nBALANCE = 100000\n\nアプリはこの結果を『残高100,000円』として画面に表示します。"];
document.getElementById('s0console').textContent=t[i]||t[4]}
function renderLab(lab){topNav(lab);runtime={lab:lab,mode:'basic',selected:0,state:Object.assign({},lab.initial),diff:['まだ状態変更はありません。'],doneActions:[]};drawLab()}
function drawLab(){const r=runtime,l=r.lab;document.getElementById('app').innerHTML=`<section class="card labHero"><div class="num">LAB ${String(l.id).padStart(2,'0')} / ${esc(l.group)}</div><h1 style="font-size:clamp(28px,4vw,44px);margin-top:8px">${esc(l.title)}</h1><p class="muted">${esc(l.subtitle)}</p><div class="goal"><strong>このLabのゴール</strong>${esc(l.goal)}</div><div class="chips scope">${l.scope.map(x=>'<span class="chip">'+esc(x)+'</span>').join('')}</div><div class="process" id="process"></div><div class="dash"><div><h2>いまの状態</h2><div class="statusGrid" id="statusGrid"></div></div><div><h2>状態DIFF — 何が変わった？</h2><div class="diff" id="diff"></div></div></div></section><section class="card workspace"><div class="modebar"><button class="mode" data-mode="basic">基本</button><button class="mode" data-mode="select">選択</button><button class="mode" data-mode="input">入力</button></div><p class="modeNote" id="modeNote"></p><div class="workgrid"><div class="pane"><div class="ptitle">ミッション / 操作</div><div class="actionList" id="actions"></div></div><div class="pane"><div class="ptitle">SQLを考える</div><div id="challenge"></div></div><div class="pane"><div class="ptitle">実行結果 / DBコンソール</div><div class="terminal" id="terminal">SQL&gt;</div></div></div><div class="lesson"><div class="lessonBadge">💡 ここがポイント</div><div id="lesson">操作すると、SQL・結果・状態変化の意味をここに表示します。</div></div><div class="breakdown"><h2>1行分解</h2><div id="tokens" class="tokenTable"><div class="muted">まだSQLを実行していません。</div></div></div></section><section class="card quiz"><h2>理解チェック</h2><p>${esc(l.quiz.q)}</p><div class="quizOpts" id="quizOpts"></div><div class="quizResult" id="quizResult"></div></section><p class="footer">※ このLabは学習用。DBMS固有構文・本番データ変更・権限操作は実環境の標準に従ってください。</p>`;bind();updateAll()}
function bind(){document.querySelectorAll('.mode').forEach(b=>b.onclick=()=>{runtime.mode=b.dataset.mode;updateAll()});document.getElementById('quizOpts').innerHTML=runtime.lab.quiz.options.map((o,i)=>'<button class="quizOpt" data-q="'+i+'">'+esc(o)+'</button>').join('');document.querySelectorAll('[data-q]').forEach(b=>b.onclick=()=>quiz(Number(b.dataset.q)))}
function updateAll(){const r=runtime,l=r.lab;document.querySelectorAll('.mode').forEach(b=>b.classList.toggle('active',b.dataset.mode===r.mode));const notes={basic:'基本：操作ボタンを押すと、裏で実行されるSQLと結果を見ながら理解します。',select:'選択：ミッションに合うSQLを3択から選びます。',input:'入力：自分でSQLを書いて実行します。空白・改行・末尾セミコロンの違いは許容します。'};document.getElementById('modeNote').textContent=notes[r.mode];document.getElementById('process').innerHTML=l.flow.map((x,i)=>'<div class="step '+(i<(r.lastFlow??-1)?'done ':'')+(i===(r.lastFlow??-1)?'active':'')+'">'+esc(x)+'</div>').join('');document.getElementById('statusGrid').innerHTML=Object.entries(r.state).map(([k,v])=>'<div class="status"><div class="k">'+esc(k)+'</div><div class="v">'+esc(v)+'</div></div>').join('');document.getElementById('diff').innerHTML=r.diff.map(x=>'<div>'+x+'</div>').join('');document.getElementById('actions').innerHTML=l.actions.map((a,i)=>'<button class="action '+(r.doneActions.includes(i)?'doneAction':'')+'" data-a="'+i+'"><span class="idx">'+String(i+1).padStart(2,'0')+'</span>'+esc(a.label)+'</button>').join('');document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{r.selected=Number(b.dataset.a);if(r.mode==='basic')execute(r.selected);else updateChallenge()});updateChallenge()}
function updateChallenge(){const r=runtime,a=r.lab.actions[r.selected],c=document.getElementById('challenge');if(r.mode==='basic'){c.innerHTML='<div class="mission"><small>操作</small><b>'+esc(a.label)+'</b><p class="muted">'+esc(a.prompt)+'</p><pre style="white-space:pre-wrap;color:#d8f5e5;background:#03090e;border:1px solid #1e3744;border-radius:9px;padding:10px">'+esc(a.statement)+'</pre><div class="muted" style="font-size:13px">左の操作ボタンを押すと実行します。</div></div>';return}if(r.mode==='select'){const shift=(r.lab.id+r.selected)%a.choices.length;r.currentChoices=a.choices.slice(shift).concat(a.choices.slice(0,shift));c.innerHTML='<div class="mission"><small>ミッション</small><b>'+esc(a.prompt)+'</b></div><div class="choiceList">'+r.currentChoices.map((x,i)=>'<button class="choice" data-c="'+i+'">'+esc(x)+'</button>').join('')+'</div><div class="feedback" id="feedback"></div>';document.querySelectorAll('[data-c]').forEach(b=>b.onclick=()=>choose(Number(b.dataset.c)));return}c.innerHTML='<div class="mission"><small>ミッション</small><b>'+esc(a.prompt)+'</b></div><textarea class="codeinput" id="sqlInput" placeholder="SQLを入力"></textarea><button class="run" id="runSql">▶ SQLを実行</button><div class="feedback" id="feedback"></div>';document.getElementById('runSql').onclick=runInput}
function norm(s){return String(s).trim().replace(/;\s*$/,'').replace(/\s+/g,' ').toUpperCase()}
function choose(i){const a=runtime.lab.actions[runtime.selected],btns=[...document.querySelectorAll('[data-c]')],f=document.getElementById('feedback');const picked=(runtime.currentChoices||a.choices)[i];const ok=norm(picked)===norm(a.statement);btns.forEach((b,n)=>{b.classList.remove('good','bad');if(n===i)b.classList.add(ok?'good':'bad')});if(ok){f.textContent='✅ 正解。実行します。';f.className='feedback ok';execute(runtime.selected)}else{f.textContent='惜しい。対象・条件・SQLの役割を見直してみよう。';f.className='feedback ng'}}
function runInput(){const a=runtime.lab.actions[runtime.selected],v=document.getElementById('sqlInput').value,f=document.getElementById('feedback');if(norm(v)===norm(a.statement)){f.textContent='✅ 正解。実行します。';f.className='feedback ok';execute(runtime.selected)}else{f.textContent='まだ一致していません。キーワード・対象表・WHERE条件を確認しよう。';f.className='feedback ng'}}
function execute(i){const r=runtime,a=r.lab.actions[i];r.selected=i;r.lastFlow=a.flow;r.state=Object.assign(r.state,a.changes);r.diff=Object.entries(a.changes).map(([k,v])=>'<b>'+esc(k)+'</b> → '+esc(v));if(!r.doneActions.includes(i))r.doneActions.push(i);if(r.doneActions.length===r.lab.actions.length)store.set(key(r.lab.id),'true');updateAll();document.getElementById('terminal').textContent='SQL> '+a.statement+'\n\n'+a.console;document.getElementById('lesson').textContent=a.lesson;document.getElementById('tokens').innerHTML=a.tokens.map(t=>'<div class="tokenRow"><div class="token">'+esc(t[0])+'</div><div class="explain">'+esc(t[1])+'</div></div>').join('')}
function quiz(i){const q=runtime.lab.quiz,btns=[...document.querySelectorAll('[data-q]')],r=document.getElementById('quizResult');btns.forEach((b,n)=>{b.classList.remove('correct','wrong');if(n===i)b.classList.add(n===q.answer?'correct':'wrong')});if(i===q.answer){r.textContent='✅ 正解。'+q.why;r.style.color='var(--ok)'}else{r.textContent='惜しい。'+q.why;r.style.color='var(--warn)'}}
function route(){if(!location.hash||location.hash==='#home'){home();return}const l=curLab();if(l)renderLab(l);else home()}
window.addEventListener('hashchange',route);route();